#!/usr/bin/env bash

YELLOW="\e[93m"
GREEN="\e[32m"
RED="\e[31m"
ENDCOLOR="\e[0m"

printMessage() {
    printf "${YELLOW}🍋 Lemonade : $1${ENDCOLOR}\n"
}

printSuccess() {
    printf "${GREEN}🍋 Lemonade : $1${ENDCOLOR}\n"
}

printError() {
    printf "${RED}❌ Lemonade : $1${ENDCOLOR}\n"
}

printMessage "Running local Lemonade pre-push hook."

printMessage "Auto formatting code ..."

# Check if there are any dart analyze issues
analyze_output=$(dart analyze 2>&1)
if [[ "$analyze_output" != *"No issues found!"* ]]; then
    printError "Error in dart analysis. Aborting commit."
	echo -e "Failed files:\n$analyze_output"
    exit 1
fi

if [[ `git status --porcelain` ]]; then
    printError "This script needs to run against committed code only. Please commit or stash you changes."
    exit 1
fi
