targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: app|lib/graphql/schema.graphql
          when_extensions:
            when: true
            maybeWhen: true
          global_enum_fallbacks: true
          type_overrides:
            DateTimeISO:
              name: DateTime
            JSON:
              name: Map<String, dynamic>
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: app|lib/graphql/schema.graphql
          type_overrides:
            DateTimeISO:
              name: DateTime
            JSON:
              name: Map<String, dynamic>
          custom_serializers:
            - import: "package:app/serializers/datetime_iso_serializer.dart"
              name: DateTimeISOSerializer
            - import: "package:app/serializers/json_serializer.dart"
              name: JSONSerializer