targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: app|lib/schemas/ai/schema.graphql
          when_extensions:
            when: true
            maybeWhen: true
          global_enum_fallbacks: true
          type_overrides:
            DateTimeISO:
              name: DateTime
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: app|lib/schemas/ai/schema.graphql
          type_overrides:
              DateTimeISO:
                name: DateTime
          custom_serializers:
            - import: "package:app/serializers/datetime_iso_serializer.dart"
              name: DateTimeISOSerializer