targets:
  $default:
    builders:
      graphql_codegen:
        options:
          scopes:
            - lib/graphql/ai/**
            - lib/graphql/backend/**
          scalars:
            DateTimeISO:
              type: DateTime
            MongoID:
              type: String
            JSON:
              type: Map<String, dynamic>
          clients:
            - graphql_flutter