targets:
  $default:
    builders:
      graphql_codegen:
        options:
          scopes:
            - lib/graphql/ai/**
            - lib/graphql/backend/**
            - lib/graphql/cubejs/**
            - lib/graphql/farcaster_airstack/**
          scalars:
            DateTimeISO:
              type: DateTime
            MongoID:
              type: String
            JSON:
              type: dynamic
            Map:
              type: Map<String, dynamic>
            Time:
              type: DateTime
            Identity:
              type: String
          clients:
            - graphql_flutter