definitions:
  instance_mac_mini: &instance_mac_mini
    instance_type: mac_mini_m1
    max_build_duration: 75
  env_versions: &env_versions
    flutter: stable
    xcode: latest
    cocoapods: default
  integrations:
    app_store_connect_integrations: &app_store_connect_integrations
      app_store_connect: Lemonade
  environment:
    load_environment_values: &load_environment_values
      groups:
        - google_credentials 
        - env_values
    ios_signing_staging: &ios_signing_staging
      ios_signing:
        distribution_type: app_store
        bundle_identifier: social.lemonade.app.staging
      vars:
        APP_ID: 6450680676
    ios_signing_production: &ios_signing_production
      ios_signing:
        distribution_type: app_store
        bundle_identifier: social.lemonade.app
      vars:
        APP_ID: 6450694884
    android_signing_staging: &android_signing_staging
      android_signing:
        - Lemonade
      vars:
        PACKAGE_NAME: "social.lemonade.app.staging"
        GOOGLE_PLAY_TRACK: "internal"
    android_signing_production: &android_signing_production
      android_signing:
        - Lemonade
      vars:
        PACKAGE_NAME: "social.lemonade.app"
        GOOGLE_PLAY_TRACK: "internal"
  artifacts:
    - &ipa build/ios/ipa/*.ipa
    - &xcode_log /tmp/xcodebuild_logs/*.log
    - &dsym $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    - &app $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    - &apk build/**/outputs/apk/**/*.apk
    - &aab build/**/outputs/bundle/**/*.aab
    - &android_log build/**/outputs/**/mapping.txt
    - &flutter_log flutter_drive.log
  scripts:
    - &load_env_files
      name: Setup Staging ENV
      script: |
        #!/bin/sh
        set -e # exit on first failed command
        echo $ENV | base64 --decode > $CM_BUILD_DIR/.env
        echo $ENV_STAGING | base64 --decode > $CM_BUILD_DIR/.env.staging
        echo $ENV_PRODUCTION | base64 --decode > $CM_BUILD_DIR/.env.production
    - &use_profiles
      name: Set up code signing settings on Xcode project
      script: |
        xcode-project use-profiles  
    - &get_flutter_packages
      name: Get Flutter packages
      script: |
        flutter packages pub get
    - &install_firebase_crashlytics
      name: Install firebase crashlytics
      script: |
        flutter pub add firebase_crashlytics
    - &setup_local_properties
      name: Set up local properties
      script: |
        echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
    - &install_pods
      name: Install pods
      script: |
        find . -name "Podfile" -execdir pod install \;
    - &build_ipa_staging
      name: Build ipa staging
      script: |
        BUILD_NUMBER=$(($(app-store-connect get-latest-testflight-build-number "$APP_ID") + 1))
        flutter build ipa --release \
          --build-number=$BUILD_NUMBER \
          --export-options-plist=/Users/builder/export_options.plist \
          --flavor="staging" \
          -t "lib/main_staging.dart"
    - &build_ipa_production
      name: Build ipa production
      script: |
        BUILD_NUMBER=$(($(app-store-connect get-latest-testflight-build-number "$APP_ID") + 1))
        flutter build ipa --release \
          --build-number=$BUILD_NUMBER \
          --export-options-plist=/Users/builder/export_options.plist \
          --flavor="production" \
          -t "lib/main_production.dart"
    - &upload_staging_dsym_to_firebase
      name: Upload staging debug symbols to Firebase Crashlytics
      script: | 
        echo "Find build artifacts"
        dsymPath=$(find $CM_BUILD_DIR/build/ios/archive/Runner.xcarchive -name "*.dSYM")
        if [[ -z ${dsymPath} ]]
        then
          echo "No Staging debug symbols were found, skip publishing to Firebase Crashlytics"
        else
          echo "Publishing Staging debug symbols from $dsymPath to Firebase Crashlytics"
          ls -d -- ios/Pods/*
          $CM_BUILD_DIR/ios/Pods/FirebaseCrashlytics/upload-symbols \
            -gsp ios/config/staging/GoogleService-Info.plist -p ios $dsymPath
        fi
    - &upload_production_dsym_to_firebase
      name: Upload production debug symbols to Firebase Crashlytics
      script: | 
        echo "Find build artifacts"
        dsymPath=$(find $CM_BUILD_DIR/build/ios/archive/Runner.xcarchive -name "*.dSYM")
        if [[ -z ${dsymPath} ]]
        then
          echo "No Production debug symbols were found, skip publishing to Firebase Crashlytics"
        else
          echo "Publishing Production debug symbols from $dsymPath to Firebase Crashlytics"
          ls -d -- ios/Pods/*
          $CM_BUILD_DIR/ios/Pods/FirebaseCrashlytics/upload-symbols \
            -gsp ios/config/production/GoogleService-Info.plist -p ios $dsymPath
        fi
    - &build_apk_staging
      name: Build Android apk staging
      script: |
        BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))      
        flutter build apk --release \
          --build-number=$BUILD_NUMBER \
          --flavor="staging" \
          -t "lib/main_staging.dart"
    - &build_aab_staging
      name: Build Android appbundle staging
      script: |
        BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))      
        flutter build appbundle --release \
          --build-number=$BUILD_NUMBER \
          --flavor="staging" \
          -t "lib/main_staging.dart"
    - &build_apk_production
      name: Build Android apk production
      script: |
        BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))      
        flutter build apk --release \
          --build-number=$BUILD_NUMBER \
          --flavor="production" \
          -t "lib/main_production.dart"
    - &build_aab_production
      name: Build Android appbundle production
      script: |
        BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))      
        flutter build appbundle --release \
          --build-number=$BUILD_NUMBER \
          --flavor="production" \
          -t "lib/main_production.dart"
    - &notify_ios_staging_to_slack
      name: Notify iOS Staging app to slack
      script: | 
        ipaPath=$(find build -name "*.ipa" | head -1)
        if [[ -z ${ipaPath} ]]
        then
          echo "No .ipa were found"
        else
          echo "Publishing .ipa artifacts"
          ARTIFACT_URL=$(echo $CM_ARTIFACT_LINKS | jq -r '.[] | select(.name | endswith("'".ipa"'")) | .url')
          curl -0 -v -X POST $SLACK_WEBHOOK_URL \
          -H 'Content-type: application/json' \
          --data-raw '
          {
            "attachments": [
              {
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "🚀 Build iOS Staging app successfully"
                    }
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Build Link*:\n<https://codemagic.io/app/'"$CM_PROJECT_ID"'/build/'"$CM_BUILD_ID"'|Click here>"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Pull Request*:\n<https://github.com/'"$CM_REPO_SLUG"'/pull/'"$CM_PULL_REQUEST_NUMBER"'|Open pull request>"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Branch*\n'"$CM_BRANCH"'"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Commit*\n'"$CM_COMMIT"'"
                      }
                    ]
                  },
                  {
                    "type": "actions",
                    "elements": [
                      {
                        "type": "button",
                        "text": {
                          "type": "plain_text",
                          "text": "Download Staging App on TestFlight"
                        },
                        "url": "itms-beta://beta.itunes.apple.com/v1/app/6450680676"
                      }
                    ]
                  }
                ]
              }
            ]
          }'
        fi
    - &notify_ios_production_to_slack
      name: Notify iOS Production app to slack
      script: | 
        ipaPath=$(find build -name "*.ipa" | head -1)
        if [[ -z ${ipaPath} ]]
        then
          echo "No .ipa were found"
        else
          echo "Publishing .ipa artifacts"
          ARTIFACT_URL=$(echo $CM_ARTIFACT_LINKS | jq -r '.[] | select(.name | endswith("'".ipa"'")) | .url')
          curl -0 -v -X POST $SLACK_WEBHOOK_URL \
          -H 'Content-type: application/json' \
          --data-raw '
          {
            "attachments": [
              {
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "🚀 Build iOS Production app successfully"
                    }
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Build Link*:\n<https://codemagic.io/app/'"$CM_PROJECT_ID"'/build/'"$CM_BUILD_ID"'|Click here>"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Pull Request*:\n<https://github.com/'"$CM_REPO_SLUG"'/pull/'"$CM_PULL_REQUEST_NUMBER"'|Open pull request>"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Branch*\n'"$CM_BRANCH"'"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Commit*\n'"$CM_COMMIT"'"
                      }
                    ]
                  },
                  {
                    "type": "actions",
                    "elements": [
                      {
                        "type": "button",
                        "text": {
                          "type": "plain_text",
                          "text": "Download on TestFlight"
                        },
                        "url": "itms-beta://beta.itunes.apple.com/v1/app/6450694884"
                      }
                    ]
                  }
                ]
              }
            ]
          }'
        fi
    - &notify_android_staging_to_slack
      name: Notify Android Staging app to slack
      script: | 
        apkPath=$(find build -name "*.apk" | head -1)
        if [[ -z ${apkPath} ]]
        then
          echo "No .apk were found"
        else
          echo "Publishing .apk artifacts"
          ARTIFACT_APK_URL=$(echo $CM_ARTIFACT_LINKS | jq -r '.[] | select(.name | endswith("'".apk"'")) | .url')
          curl -0 -v -X POST $SLACK_WEBHOOK_URL \
          -H 'Content-type: application/json' \
          --data-raw '
          {
            "attachments": [
              {
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "🚀 Build Android Staging app successfully"
                    }
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Build Link*:\n<https://codemagic.io/app/'"$CM_PROJECT_ID"'/build/'"$CM_BUILD_ID"'|Click here>"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Pull Request*:\n<https://github.com/'"$CM_REPO_SLUG"'/pull/'"$CM_PULL_REQUEST_NUMBER"'|Open pull request>"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Branch*\n'"$CM_BRANCH"'"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Commit*\n'"$CM_COMMIT"'"
                      }
                    ]
                  },
                  {
                    "type": "actions",
                    "elements": [
                      {
                        "type": "button",
                        "text": {
                          "type": "plain_text",
                          "text": "Download APK"
                        },
                        "url": "'${ARTIFACT_APK_URL}'"
                      }
                    ]
                  }
                ]
              }
            ]
          }'
        fi
    - &notify_android_production_to_slack
      name: Notify Android Production app to slack
      script: | 
        apkPath=$(find build -name "*.apk" | head -1)
        if [[ -z ${apkPath} ]]
        then
          echo "No .apk were found"
        else
          echo "Publishing .apk artifacts"
          ARTIFACT_APK_URL=$(echo $CM_ARTIFACT_LINKS | jq -r '.[] | select(.name | endswith("'".apk"'")) | .url')
          curl -0 -v -X POST $SLACK_WEBHOOK_URL \
          -H 'Content-type: application/json' \
          --data-raw '
          {
            "attachments": [
              {
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "🚀 Build Android Production app successfully"
                    }
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Build Link*:\n<https://codemagic.io/app/'"$CM_PROJECT_ID"'/build/'"$CM_BUILD_ID"'|Click here>"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Pull Request*:\n<https://github.com/'"$CM_REPO_SLUG"'/pull/'"$CM_PULL_REQUEST_NUMBER"'|Open pull request>"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Branch*\n'"$CM_BRANCH"'"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Commit*\n'"$CM_COMMIT"'"
                      }
                    ]
                  },
                  {
                    "type": "actions",
                    "elements": [
                      {
                        "type": "button",
                        "text": {
                          "type": "plain_text",
                          "text": "Download APK"
                        },
                        "url": "'${ARTIFACT_APK_URL}'"
                      }
                    ]
                  }
                ]
              }
            ]
          }'
        fi
  email_staging: &email_staging
    email:
      recipients:
        - sieu@coderpush.com
        - thinh@coderpush.com
      notify:
        success: true
        failure: false
  email_production: &email_production
    email:
      recipients:
        - sieu@coderpush.com
        - thinh@coderpush.com
        # - kc@lemonade.social
        # - chris@lemonade.social
        # - jakob@lemonade.social
        # - pranoti@lemonade.social
        # - rishi@lemonade.social
        # - david@lemonade.social
      notify:
        success: true
        failure: false
  ios_app_store_publish: &ios_app_store_publish
    app_store_connect:
      auth: integration
      submit_to_testflight: true
      submit_to_app_store: false
  android_publish: &android_publish
    google_play:
      credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
      track: $GOOGLE_PLAY_TRACK
      submit_as_draft: true
workflows:
  # Build iOS Staging 
  ios-staging:
    name: iOS Staging
    <<: *instance_mac_mini
    integrations:
      <<: *app_store_connect_integrations
    environment:
      <<: *env_versions
      <<: *load_environment_values
      <<: *ios_signing_staging
    triggering:
      events:
        - push
      branch_patterns: 
        - pattern: master
      cancel_previous_builds: true
    scripts:
      - *load_env_files
      - *use_profiles
      - *get_flutter_packages
      - *install_firebase_crashlytics
      - *install_pods
      - *build_ipa_staging
    artifacts:
      - *ipa
      - *xcode_log
      - *dsym
      - *app
    publishing:
      <<: *ios_app_store_publish
      <<: *email_staging
      scripts:
        - *upload_staging_dsym_to_firebase
        - *notify_ios_staging_to_slack
  # Build Android Staging
  android-staging:
    name: Android Staging
    <<: *instance_mac_mini
    environment:
      <<: *env_versions
      <<: *load_environment_values
      <<: *android_signing_staging
    triggering:
      events:
        - push
      branch_patterns: 
        - pattern: master
      cancel_previous_builds: true
    scripts:
      - *load_env_files
      - *setup_local_properties
      - *get_flutter_packages
      - *build_apk_staging
      - *build_aab_staging
    artifacts:
      - *apk
      - *aab
      - *android_log
    publishing:
      <<: *android_publish
      <<: *email_staging
      scripts:
        - *notify_android_staging_to_slack
  # Build iOS Production
  ios-production:
    name: iOS Production
    <<: *instance_mac_mini
    integrations:
      <<: *app_store_connect_integrations
    environment:
      <<: *env_versions
      <<: *load_environment_values
      <<: *ios_signing_production
    triggering:
      events:
        - tag
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: true
    scripts:
      - *load_env_files
      - *use_profiles
      - *get_flutter_packages
      - *install_firebase_crashlytics
      - *install_pods
      - *build_ipa_production
    artifacts:
      - *ipa
      - *xcode_log
      - *dsym
      - *app
    publishing:
      <<: *ios_app_store_publish
      <<: *email_production
      scripts:
        - *upload_production_dsym_to_firebase
        - *notify_ios_production_to_slack

  # Build Android Production
  android-production:
    name: Android Production
    <<: *instance_mac_mini
    environment:
      <<: *env_versions
      <<: *load_environment_values
      <<: *android_signing_production
    triggering:
      events:
        - tag
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: true
    scripts:
      - *load_env_files
      - *setup_local_properties
      - *get_flutter_packages
      - *build_apk_production
      - *build_aab_production
    artifacts:
      - *apk
      - *aab
      - *android_log
    publishing:
      <<: *android_publish
      <<: *email_production
      scripts:
        - *notify_android_production_to_slack