import 'package:timezone/timezone.dart' as tz;

class EventConstants {
  /// Guest limit per 2
  static String defaultEventGuestLimitPer = '2';

  /// Guest limit 100
  static String defaultEventGuestLimit = '100';

  static final List<Map<String, String>> timezoneOptions =
      _generateTimezoneOptions();

  static List<Map<String, String>> _generateTimezoneOptions() {
    final Map<String, String> timezoneData = {
      'Niue': 'Pacific/Niue',
      'Pago Pago': 'Pacific/Pago_Pago',
      'Hawaii Time': 'Pacific/Honolulu',
      'Rarotonga': 'Pacific/Rarotonga',
      'Tahiti': 'Pacific/Tahiti',
      'Marquesas': 'Pacific/Marquesas',
      'Alaska Time': 'America/Anchorage',
      'Gambier': 'Pacific/Gambier',
      'Pacific Time': 'America/Los_Angeles',
      'Pacific Time - Tijuana': 'America/Tijuana',
      'Pacific Time - Vancouver': 'America/Vancouver',
      'Pacific Time - Whitehorse': 'America/Whitehorse',
      'Pitcairn': 'Pacific/Pitcairn',
      'Mountain Time': 'America/Denver',
      'Mountain Time - Arizona': 'America/Phoenix',
      'Mountain Time - Chihuahua, Mazatlan': 'America/Mazatlan',
      'Mountain Time - Dawson Creek': 'America/Dawson_Creek',
      'Mountain Time - Edmonton': 'America/Edmonton',
      'Mountain Time - Hermosillo': 'America/Hermosillo',
      'Mountain Time - Yellowknife': 'America/Yellowknife',
      'Belize': 'America/Belize',
      'Central Time': 'America/Chicago',
      'Central Time - Mexico City': 'America/Mexico_City',
      'Central Time - Regina': 'America/Regina',
      'Central Time - Tegucigalpa': 'America/Tegucigalpa',
      'Central Time - Winnipeg': 'America/Winnipeg',
      'Costa Rica': 'America/Costa_Rica',
      'El Salvador': 'America/El_Salvador',
      'Galapagos': 'Pacific/Galapagos',
      'Guatemala': 'America/Guatemala',
      'Managua': 'America/Managua',
      'America Cancun': 'America/Cancun',
      'Bogota': 'America/Bogota',
      'Easter Island': 'Pacific/Easter',
      'Eastern Time': 'America/New_York',
      'Eastern Time - Iqaluit': 'America/Iqaluit',
      'Eastern Time - Toronto': 'America/Toronto',
      'Guayaquil': 'America/Guayaquil',
      'Havana': 'America/Havana',
      'Jamaica': 'America/Jamaica',
      'Lima': 'America/Lima',
      'Nassau': 'America/Nassau',
      'Panama': 'America/Panama',
      'Port-au-Prince': 'America/Port-au-Prince',
      'Rio Branco': 'America/Rio_Branco',
      'Atlantic Time - Halifax': 'America/Halifax',
      'Barbados': 'America/Barbados',
      'Bermuda': 'Atlantic/Bermuda',
      'Boa Vista': 'America/Boa_Vista',
      'Caracas': 'America/Caracas',
      'Curacao': 'America/Curacao',
      'Grand Turk': 'America/Grand_Turk',
      'Guyana': 'America/Guyana',
      'La Paz': 'America/La_Paz',
      'Manaus': 'America/Manaus',
      'Martinique': 'America/Martinique',
      'Port of Spain': 'America/Port_of_Spain',
      'Porto Velho': 'America/Porto_Velho',
      'Puerto Rico': 'America/Puerto_Rico',
      'Santo Domingo': 'America/Santo_Domingo',
      'Thule': 'America/Thule',
      'Newfoundland Time - St. Johns': 'America/St_Johns',
      'Araguaina': 'America/Araguaina',
      'Asuncion': 'America/Asuncion',
      'Belem': 'America/Belem',
      'Buenos Aires': 'America/Argentina/Buenos_Aires',
      'Campo Grande': 'America/Campo_Grande',
      'Cayenne': 'America/Cayenne',
      'Cuiaba': 'America/Cuiaba',
      'Fortaleza': 'America/Fortaleza',
      'Godthab': 'America/Godthab',
      'Maceio': 'America/Maceio',
      'Miquelon': 'America/Miquelon',
      'Montevideo': 'America/Montevideo',
      'Palmer': 'Antarctica/Palmer',
      'Paramaribo': 'America/Paramaribo',
      'Punta Arenas': 'America/Punta_Arenas',
      'Recife': 'America/Recife',
      'Rothera': 'Antarctica/Rothera',
      'Salvador': 'America/Bahia',
      'Santiago': 'America/Santiago',
      'Stanley': 'Atlantic/Stanley',
      'Noronha': 'America/Noronha',
      'Sao Paulo': 'America/Sao_Paulo',
      'South Georgia': 'Atlantic/South_Georgia',
      'Azores': 'Atlantic/Azores',
      'Cape Verde': 'Atlantic/Cape_Verde',
      'Scoresbysund': 'America/Scoresbysund',
      'Abidjan': 'Africa/Abidjan',
      'Accra': 'Africa/Accra',
      'Bissau': 'Africa/Bissau',
      'Canary Islands': 'Atlantic/Canary',
      'Casablanca': 'Africa/Casablanca',
      'Danmarkshavn': 'America/Danmarkshavn',
      'Dublin': 'Europe/Dublin',
      'El Aaiun': 'Africa/El_Aaiun',
      'Faeroe': 'Atlantic/Faroe',
      'GMT (no daylight saving)': 'Etc/GMT',
      'Etc/Greenwich': 'Etc/Greenwich',
      'Lisbon': 'Europe/Lisbon',
      'London': 'Europe/London',
      'Monrovia': 'Africa/Monrovia',
      'Reykjavik': 'Atlantic/Reykjavik',
      'UTC': 'UTC',
      'Algiers': 'Africa/Algiers',
      'Amsterdam': 'Europe/Amsterdam',
      'Andorra': 'Europe/Andorra',
      'Berlin': 'Europe/Berlin',
      'Brussels': 'Europe/Brussels',
      'Budapest': 'Europe/Budapest',
      'Central European Time - Belgrade': 'Europe/Belgrade',
      'Central European Time - Prague': 'Europe/Prague',
      'Ceuta': 'Africa/Ceuta',
      'Copenhagen': 'Europe/Copenhagen',
      'Gibraltar': 'Europe/Gibraltar',
      'Lagos': 'Africa/Lagos',
      'Luxembourg': 'Europe/Luxembourg',
      'Madrid': 'Europe/Madrid',
      'Malta': 'Europe/Malta',
      'Monaco': 'Europe/Monaco',
      'Ndjamena': 'Africa/Ndjamena',
      'Oslo': 'Europe/Oslo',
      'Paris': 'Europe/Paris',
      'Rome': 'Europe/Rome',
      'Stockholm': 'Europe/Stockholm',
      'Tirane': 'Europe/Tirane',
      'Tunis': 'Africa/Tunis',
      'Vienna': 'Europe/Vienna',
      'Warsaw': 'Europe/Warsaw',
      'Zurich': 'Europe/Zurich',
      'Amman': 'Asia/Amman',
      'Athens': 'Europe/Athens',
      'Beirut': 'Asia/Beirut',
      'Bucharest': 'Europe/Bucharest',
      'Harare': 'Africa/Harare',
      'Cairo': 'Africa/Cairo',
      'Chisinau': 'Europe/Chisinau',
      'Damascus': 'Asia/Damascus',
      'Gaza': 'Asia/Gaza',
      'Helsinki': 'Europe/Helsinki',
      'Jerusalem': 'Asia/Jerusalem',
      'Johannesburg': 'Africa/Johannesburg',
      'Khartoum': 'Africa/Khartoum',
      'Kiev': 'Europe/Kiev',
      'Maputo': 'Africa/Maputo',
      'Moscow-01 - Kaliningrad': 'Europe/Kaliningrad',
      'Nicosia': 'Asia/Nicosia',
      'Riga': 'Europe/Riga',
      'Sofia': 'Europe/Sofia',
      'Tallinn': 'Europe/Tallinn',
      'Tripoli': 'Africa/Tripoli',
      'Vilnius': 'Europe/Vilnius',
      'Windhoek': 'Africa/Windhoek',
      'Baghdad': 'Asia/Baghdad',
      'Istanbul': 'Europe/Istanbul',
      'Minsk': 'Europe/Minsk',
      'Moscow+00 - Moscow': 'Europe/Moscow',
      'Nairobi': 'Africa/Nairobi',
      'Qatar': 'Asia/Qatar',
      'Riyadh': 'Asia/Riyadh',
      'Syowa': 'Antarctica/Syowa',
      'Tehran': 'Asia/Tehran',
      'Baku': 'Asia/Baku',
      'Dubai': 'Asia/Dubai',
      'Mahe': 'Indian/Mahe',
      'Mauritius': 'Indian/Mauritius',
      'Moscow+01 - Samara': 'Europe/Samara',
      'Reunion': 'Indian/Reunion',
      'Tbilisi': 'Asia/Tbilisi',
      'Yerevan': 'Asia/Yerevan',
      'Kabul': 'Asia/Kabul',
      'Aqtau': 'Asia/Aqtau',
      'Aqtobe': 'Asia/Aqtobe',
      'Ashgabat': 'Asia/Ashgabat',
      'Dushanbe': 'Asia/Dushanbe',
      'Karachi': 'Asia/Karachi',
      'Kerguelen': 'Indian/Kerguelen',
      'Maldives': 'Indian/Maldives',
      'Mawson': 'Antarctica/Mawson',
      'Moscow+02 - Yekaterinburg': 'Asia/Yekaterinburg',
      'Tashkent': 'Asia/Tashkent',
      'Colombo': 'Asia/Colombo',
      'India Standard Time': 'Asia/Calcutta',
      'Kathmandu': 'Asia/Kathmandu',
      'Almaty': 'Asia/Almaty',
      'Bishkek': 'Asia/Bishkek',
      'Chagos': 'Indian/Chagos',
      'Dhaka': 'Asia/Dhaka',
      'Moscow+03 - Omsk': 'Asia/Omsk',
      'Thimphu': 'Asia/Thimphu',
      'Vostok': 'Antarctica/Vostok',
      'Cocos': 'Indian/Cocos',
      'Rangoon': 'Asia/Yangon',
      'Bangkok': 'Asia/Bangkok',
      'Christmas': 'Indian/Christmas',
      'Davis': 'Antarctica/Davis',
      'Hanoi': 'Asia/Saigon',
      'Hovd': 'Asia/Hovd',
      'Jakarta': 'Asia/Jakarta',
      'Moscow+04 - Krasnoyarsk': 'Asia/Krasnoyarsk',
      'Brunei': 'Asia/Brunei',
      'China Time - Beijing': 'Asia/Shanghai',
      'Choibalsan': 'Asia/Choibalsan',
      'Hong Kong': 'Asia/Hong_Kong',
      'Kuala Lumpur': 'Asia/Kuala_Lumpur',
      'Macau': 'Asia/Macau',
      'Makassar': 'Asia/Makassar',
      'Manila': 'Asia/Manila',
      'Moscow+05 - Irkutsk': 'Asia/Irkutsk',
      'Singapore': 'Asia/Singapore',
      'Taipei': 'Asia/Taipei',
      'Ulaanbaatar': 'Asia/Ulaanbaatar',
      'Western Time - Perth': 'Australia/Perth',
      'Pyongyang': 'Asia/Pyongyang',
      'Dili': 'Asia/Dili',
      'Jayapura': 'Asia/Jayapura',
      'Moscow+06 - Yakutsk': 'Asia/Yakutsk',
      'Palau': 'Pacific/Palau',
      'Seoul': 'Asia/Seoul',
      'Tokyo': 'Asia/Tokyo',
      'Central Time - Darwin': 'Australia/Darwin',
      "Dumont D'Urville": 'Antarctica/DumontDUrville',
      'Eastern Time - Brisbane': 'Australia/Brisbane',
      'Guam': 'Pacific/Guam',
      'Moscow+07 - Vladivostok': 'Asia/Vladivostok',
      'Port Moresby': 'Pacific/Port_Moresby',
      'Truk': 'Pacific/Chuuk',
      'Central Time - Adelaide': 'Australia/Adelaide',
      'Casey': 'Antarctica/Casey',
      'Eastern Time - Hobart': 'Australia/Hobart',
      'Eastern Time - Melbourne, Sydney': 'Australia/Sydney',
      'Efate': 'Pacific/Efate',
      'Guadalcanal': 'Pacific/Guadalcanal',
      'Kosrae': 'Pacific/Kosrae',
      'Moscow+08 - Magadan': 'Asia/Magadan',
      'Norfolk': 'Pacific/Norfolk',
      'Noumea': 'Pacific/Noumea',
      'Ponape': 'Pacific/Pohnpei',
      'Funafuti': 'Pacific/Funafuti',
      'Kwajalein': 'Pacific/Kwajalein',
      'Majuro': 'Pacific/Majuro',
      'Moscow+09 - Petropavlovsk-Kamchatskiy': 'Asia/Kamchatka',
      'Nauru': 'Pacific/Nauru',
      'Tarawa': 'Pacific/Tarawa',
      'Wake': 'Pacific/Wake',
      'Wallis': 'Pacific/Wallis',
      'Auckland': 'Pacific/Auckland',
      'Enderbury': 'Pacific/Enderbury',
      'Fakaofo': 'Pacific/Fakaofo',
      'Fiji': 'Pacific/Fiji',
      'Tongatapu': 'Pacific/Tongatapu',
      'Apia': 'Pacific/Apia',
      'Kiritimati': 'Pacific/Kiritimati',
      'Canberra': 'Australia/Canberra',
    };

    return timezoneData.entries.map((entry) {
      final String key = entry.key;
      final String value = entry.value;
      final location = tz.getLocation(value);
      final now = tz.TZDateTime.now(location);
      final offset = now.timeZoneOffset;
      final String zz = offset.isNegative
          ? '-${offset.abs().inHours.toString().padLeft(2, '0')}:${(offset.abs().inMinutes % 60).toString().padLeft(2, '0')}'
          : '+${offset.inHours.toString().padLeft(2, '0')}:${(offset.inMinutes % 60).toString().padLeft(2, '0')}';
      return {
        'value': value,
        'text': '(GMT$zz) $key',
        'short': 'GMT$zz',
      };
    }).toList();
  }
}

class EventDateTimeConstants {
  static final DateTime currentDateTime = DateTime.now();

  static final DateTime defaultStartDateTime = DateTime.utc(
    currentDateTime.year,
    currentDateTime.month,
    currentDateTime.day + 3,
    10,
  );

  static final DateTime defaultEndDateTime = DateTime.utc(
    currentDateTime.year,
    currentDateTime.month,
    currentDateTime.day + 6,
    18,
  );
}
