// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_production.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA61EgHIslmv8VOI_DW1uzFNqhST6lSSiE',
    appId: '1:1008216646580:web:03b585463050278e4888e1',
    messagingSenderId: '1008216646580',
    projectId: 'lemonade-53666233',
    authDomain: 'lemonade-53666233.firebaseapp.com',
    storageBucket: 'lemonade-53666233.appspot.com',
    measurementId: 'G-42WNLGXYKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqbYBuoZCvFCttjdbS1WzJCC72wFFiBDA',
    appId: '1:1008216646580:android:44583057043f72104888e1',
    messagingSenderId: '1008216646580',
    projectId: 'lemonade-53666233',
    storageBucket: 'lemonade-53666233.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAliG_RWzEnlR-kJ8Ro--6AfuTT46UP-b4',
    appId: '1:1008216646580:ios:5564067f544e45ac4888e1',
    messagingSenderId: '1008216646580',
    projectId: 'lemonade-53666233',
    storageBucket: 'lemonade-53666233.appspot.com',
    iosBundleId: 'social.lemonade.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAliG_RWzEnlR-kJ8Ro--6AfuTT46UP-b4',
    appId: '1:1008216646580:ios:5564067f544e45ac4888e1',
    messagingSenderId: '1008216646580',
    projectId: 'lemonade-53666233',
    storageBucket: 'lemonade-53666233.appspot.com',
    iosBundleId: 'social.lemonade.app',
  );
}