enum NotificationSettingType {
  admin([
    'admin_payment_verification',
  ]),
  chat([
    'chat_message',
  ]),
  event([
    'event_announce',
    'event_approve',
    'event_broadcast_created',
    'event_broadcast_deactivated',
    'event_broadcast_deleted',
    'event_broadcast_ended',
    'event_broadcast_rescheduled',
    'event_broadcast_started',
    'event_cancellation',
    'event_chat_announce',
    'event_cohost_request',
    'event_cohost_request_announce',
    'event_donation',
    'event_invite',
    'event_invite_verify_accept_request',
    'event_invite_verify_request',
    'event_payment_split_remove',
    'event_payment_split_request',
    'event_payment_split_request_accept',
    'event_payment_split_request_decline',
    'event_unlock_verify_accept_request',
    'event_unlock_verify_request',
    'event_update',
  ]),
  payment([
    'payment_assign',
    'payment_authorized',
    'payment_failed',
    'payment_refunded',
  ]),
  payments([
    'payments_captured_summary',
    'payments_wired_summary',
  ]),
  place([
    'place_reservation_delete',
    'place_reservation_request',
    'place_reservation_request_accept',
    'place_reservation_request_decline',
  ]),
  reservation([
    'reservation_accept',
    'reservation_decline',
  ]),
  room([
    'room_invite',
    'room_started',
  ]),
  store([
    'store_order_accepted',
    'store_order_awaiting_pickup',
    'store_order_cancelled',
    'store_order_declined',
    'store_order_delivered',
    'store_order_delivery_confirmed',
    'store_order_in_transit',
    'store_order_pending',
    'store_order_preparing',
  ]),
  user([
    'user_contact_signup',
    'user_discovery_match',
    'user_friendship_request',
    'user_friendship_request_accept',
  ]);

  final List<String> notificationDetail;

  const NotificationSettingType(this.notificationDetail);
}
