name: Flutter CI
on: push
jobs:
  build:
    if: github.event.pull_request.draft == false
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.19.6'
          channel: 'stable'

      # Get flutter dependencies.
      - run: flutter pub get
      
      - name: Create environment files
        run: |
          touch .env
          touch .env.staging
          touch .env.production

      # Check for any formatting issues in the code.
      - name: Format code
        run: dart format --set-exit-if-changed .  

      - name: Run build_runner
        run: |
          flutter packages pub run build_runner build --delete-conflicting-outputs
      
      - name: Generate i18n files
        run: |
          dart run slang  

      - uses: invertase/github-action-dart-analyzer@v1
        with:
          # (Optional) Treat info level issues as fatal.
          fatal-infos: false

          # (Optional) Treat warning level issues as fatal
          # (defaults to true).
          fatal-warnings: false

          # (Optional) Whether to add annotations to GitHub actions summary / PR
          # review files.
          # (defaults to true).
          annotate: true

          # (Optional) If set to true only annotations will be created and the
          # GitHub action itself will not fail on Dart analyzer problems. 
          # (defaults to false).
          annotate-only: false

          # (Optional) The working directory to run the Dart analyzer in 
          # (defaults to `./`).
          working-directory: ./